---
- hosts: webservers
  tasks:

- name: hostname | Configure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: hostname | Add hostname hosts to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ inventory_hostname }}'

- name: Disable USERGROUPS_ENABLE for Umask 022
  lineinfile:
    dest: /etc/login.defs
    regexp: ^USERGROUPS_ENAB
    line: "#USERGROUPS_ENAB yes"
    state: present
    backrefs: yes

- name: Update the apt cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_expiration }}"

- name: 4 Add ufw https service.
  become: yes
  ansible.community.ufw:
    service: https
    permanent: yes
    state: enabled
    immediate: true

#Build Packages

- name: 14 Install needed packages
  become: yes
  apt:
    name: 
      - net-tools
      - git
      - build-essential 
      - libssl-dev 
      - libffi-dev 
      - python3-dev
      - python3-venv
      - docker-ce
      - python3-docker
      - python-pip
    state: present

- name: Clone Your WebApp.
  become: yes
  ansible.builtin.git:
    repo: https://github.com/yourusername/yourrepo.git
    dest: /home/{{ansible_user}}/yourrepo/
    clone: yes
    force: yes